server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name aact-strategy.duckdns.org 13.125.227.73 _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name aact-strategy.duckdns.org;
    ssl_certificate /etc/letsencrypt/live/aact-strategy.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aact-strategy.duckdns.org/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /home/ubuntu/aact-project;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /tech {
        return 301 /tech/;
    }

    location /tech/ {
        alias /home/ubuntu/key-tech-trend/;
        index index.html;
        try_files $uri $uri/ /tech/index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
